# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/snakemake/snakefmt
    rev: v0.8.4
    hooks:
    -   id: snakefmt
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120, --ignore=E203]
-   repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    -   id: jupyter-notebook-cleanup
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        verbose: true
        args: ["--check-untyped-defs"]
        additional_dependencies: [types-all, pandas-stubs]
